---
title: "Activity monitoring data"
author: "Tyler Burleigh"
date: "3/18/2019"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, error=FALSE, warning=FALSE)
library("tidyverse")
library("data.table")
library("lubridate")
library("chron")
library("knitr")
```

## Read data

```{r read-data}
# Code for reading in the dataset and/or processing the data
df <- fread("data/activity.csv")
```

## Histogram of daily steps

```{r histogram}
# Histogram of the total number of steps taken each day
df %>% 
  group_by(date) %>% # Group by date
  summarize(steps = sum(steps)) %>% # Sum steps
  ggplot(aes(steps)) + # Create a histogram using ggplot
    geom_histogram(bins = 20) +
    ggtitle("Histogram of Daily Steps") +
    xlab("Daily Steps") + 
    ylab("Frequency") +
    theme(plot.margin = unit(c(1,1,1,1), "cm"))
```

## Mean / median daily steps

```{r mean-median}
# Mean and median number of steps taken each day
(df %>% 
  group_by(date) %>% # Group by date
  summarize(steps = sum(steps)) %>% # Sum steps
  select(steps) %>% # Select steps variable
  summary(steps))[3:4] # Rows 3 and 4 of the summary object
```

## Time series plot

```{r time-series}
# Time series plot of the average number of steps taken
df %>% 
  group_by(date) %>% # Group by date
  summarize(steps = mean(steps, na.rm = T)) %>% # Mean steps
  filter(!is.na(steps)) %>% # Remove days with NA steps
  mutate(date = as.POSIXct(date)) %>%
  ggplot(., aes(x = date, y = steps)) +
    geom_line(color = "red") +
    ggtitle("Average Daily Steps Across Time") +
    theme(plot.margin = unit(c(1,1,1,1), "cm"))
```

## 5-minute interval with max steps, on average

```{r interval-max-avg}
# The 5-minute interval that, on average, contains the maximum number of steps
df %>% 
  group_by(interval) %>% # Group by interval
  summarize(steps = round(mean(steps, na.rm = T))) %>% # Mean steps
  arrange(desc(steps)) %>% # Order by steps
  head(1) %>% # Show only the first result
  kable()
```

## Missing data imputation

```{r impute}
# Code to describe and show a strategy for imputing missing data
# This will replace NA values with the median steps for an interval
df %>%
    mutate(steps = replace_na(steps, median(df[interval == interval]$steps, na.rm=T))) -> df2
```


## Histogram post-imputation

```{r histogram-post-impute}
# Histogram of the total number of steps taken each day after missing values are imputed
df2 %>% 
  group_by(date) %>% # Group by date
  summarize(steps = sum(steps)) %>% # Sum steps
  ggplot(aes(steps)) + # Create a histogram using ggplot
    geom_histogram(bins = 20) +
    ggtitle("Histogram of Daily Steps, Post-Imputation") +
    xlab("Daily Steps") + 
    ylab("Frequency") +
    theme(plot.margin = unit(c(1,1,1,1), "cm"))
```

# Steps by interval and weekdays vs. weekends

```{r steps-by-interval-weekend-weekday}
# Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends
df2 %>% # Use imputed dataset
  mutate(day_type = ifelse(is.weekend(date), "weekend", "weekday")) %>%
  group_by(day_type, interval) %>% # Group by day_type and interval
  summarize(steps = mean(steps)) %>% # Mean steps
  ggplot(aes(x = interval, y = steps)) + # Create bar plot with steps by interval and day_type facets
    geom_bar(position = "dodge", stat="identity") + 
    facet_grid(day_type ~ .) +
    ggtitle("Histogram of Steps by Interval and Weekday/Weekend") +
    xlab("Interval") + 
    ylab("Average Steps")
```
